### ISSUE TITLE
High CPU and Ram usage for a simple md file

### ISSUE THREAD

**Issue by huyhoang160593** [mdSilo/mdSilo#12]
With only open a md file with 10 line, the ram usage are up to 2GB and the CPU most of the time is 100% ??? This app seem promise but the memory leak are pretty terrible

**Comment by danloh** [comment]
Can I have more information about the platform?  Thanks

**Comment by danloh** [comment]
Have made some improvements on v0.4.5:  https://mdsilo.com/ 

And no more information to investigate right now, so I want to close this issue. 

feel free to re-open with further information.
