### ISSUE TITLE
How to manage folders inside mdsilo, please add outline view. 

### ISSUE THREAD

**Issue by bayeslearnerold** [mdSilo/mdSilo#14]
This is a great alternative to typora(caret) and obsidian combined.  please complete these basic features.

**Comment by danloh** [comment]
Would you like explaining more detail for the outline view?  Thanks.

**Comment by bayeslearnerold** [comment]
In terms of folder management, I mean adding functions to create/renaming/deleting folders.  I still use folders to organize notes. 

In terms of outlines, I would like to quickly have an overview of the current document and jump around sections.

**Comment by danloh** [comment]
Folder management:  in to-do list, 
Track issue here: https://github.com/danloh/mdSilo-app/issues/265

Outline:  TOC on doc page has shipped

**Comment by danloh** [comment]
shipped on v0.4.6
