### ISSUE TITLE
image url inserted from other tools obsidan/typora doesn't work, local image insert doesn't work either. 

### ISSUE THREAD

**Issue by bayeslearnerold** [mdSilo/mdSilo#15]
local images inserted using obsidan/typora do not display correctly.  
```
![](./assets/xxx.png)

![](assets/xxxx.png)
```

`/ insert image` also does not do anything. 

Image is displayed correctly with a weird URL `asset.localhost/...`

**Comment by danloh** [comment]
`https://asset.localhost` and `asset:` are the protocol supported by Tauri, thus the source can be loaded by the webview. 

Please use  `slash command: /image` to select and insert local image.

**Comment by bayeslearnerold** [comment]
But webview protocol syntax is not recognized by obsidian and vice versa.  Is there a way to provide compatibility?

**Comment by danloh** [comment]
Yes, there is a compatibility issue, 
mdsilo is built with Tauri and obsidian with Electron.  

Let's add this to to-do list.

**Comment by danloh** [comment]
Relative path (`./`) support shipped in v0.4.7:  https://mdsilo.com/, 
You can forget `asset:` or `https://asset.localhost` now.

I will close this issue.
