### ISSUE TITLE
mdsilo > Sponsor menu item links to 404 page

### ISSUE THREAD

**Issue by aci-d** [mdSilo/mdSilo#26]
Choosing "Sponsor" menu item from "mdSilo" top menu opens the following link in the browser: "https://mdsilo.com/sponsors"
The page is "404: This page could not be found".
Perhaps this should link to your "https://mdsilo.com/helpus" page instead?

Using mdSilo Desktop 0.5.2 on Linux

**Comment by danloh** [comment]
Thanks and fixed it
