### ISSUE TITLE
Can still access "New Writing" command when no file/folder is open - and nothing happens

### ISSUE THREAD

**Issue by aci-d** [mdSilo/mdSilo#27]
When mdSilo opens, no folder/file is automatically opened. (The sidebar shows "Open Folder" and "Open File" buttons, etc. to get you to select this)
The "New Writing" option is still available, and if selected, the "new or find" box pops up. 
- If you enter a new file name and hit enter, nothing happens (no clear user feedback but the file is not created).
- If you enter a known existing file name, it doesn't appear in the search.

Choosing to "New Writing" at this stage should be disabled (and the other menu options should probably also be disabled in this state as they don't show very useful information)
OR 
Otherwise some default folder/file should be opened on startup automatically.

Using mdSilo Desktop 0.5.2 on Linux

**Comment by danloh** [comment]
> Choosing to "New Writing" at this stage should be disabled (and the other menu options should probably also be disabled in this state as they don't show very useful information)

Ok, let's hide them ^_^
