### ISSUE TITLE
mdsmirror repository missing

### ISSUE THREAD

**Issue by aichingm** [mdSilo/mdSilo#8]
Hey @danloh,

I just stumbled across your amazing looking mdsilo and wanted jump into the code and try a few things. Reading though the source I found a mdsmirror import in one of the files, when checking the [npm.io page](https://npm.io/package/mdsmirror) it linked to a github repo which does not exist https://github.com/danloh/mdsmirror.

is this by design or a mistake? 

Best Mario

**Comment by danloh** [comment]
Sorry, will make it public later. and I will close this issue.
